//! BCH(15,5) encoder/decoder for QR format info bits.
//! Rust port of zbar/qrcode/bch15_5.{c,h}.
//! Original Copyright (C) 2008-2009 Timothy B. Terriberry (tterribe@xiph.org)
//! LGPL-2.1-or-later
//!
//! Encodes a 5-bit value into a 15-bit BCH codeword that corrects up to 3 bit
//! errors and detects up to 5. Used by `fmt_info_decode` in qrdec.

/// A cycle in GF(2⁴) generated by alpha = (x⁴+x+1), extended by 16 entries to
/// avoid mod operations.
const GF16_EXP: [u8; 31] = [
    1, 2, 4, 8, 3, 6, 12, 11, 5, 10, 7, 14, 15, 13, 9,
    1, 2, 4, 8, 3, 6, 12, 11, 5, 10, 7, 14, 15, 13, 9, 1,
];

/// Location of each integer 1..=15 in the GF16_EXP cycle. Index 0 is a
/// sentinel (-1) — callers must guard against `a == 0`.
const GF16_LOG: [i8; 16] = [
    -1, 0, 1, 4, 2, 8, 5, 10, 3, 14, 9, 7, 6, 13, 11, 12,
];

#[inline]
fn gf16_mul(a: u32, b: u32) -> u32 {
    if a == 0 || b == 0 { 0 }
    else {
        let i = GF16_LOG[a as usize] as usize + GF16_LOG[b as usize] as usize;
        GF16_EXP[i] as u32
    }
}

#[inline]
fn gf16_div(a: u32, b: u32) -> u32 {
    if a == 0 { 0 }
    else {
        let i = GF16_LOG[a as usize] as usize + 15 - GF16_LOG[b as usize] as usize;
        GF16_EXP[i] as u32
    }
}

#[inline]
fn gf16_hmul(a: u32, logb: u32) -> u32 {
    if a == 0 { 0 }
    else {
        let i = GF16_LOG[a as usize] as usize + logb as usize;
        GF16_EXP[i] as u32
    }
}

/// Compute the odd syndromes S₁, S₃, S₅ (S₂=S₁², S₄=S₂² omitted).
/// Returns `true` iff any syndrome is non-zero.
fn bch15_5_calc_syndrome(s: &mut [u32; 3], y: u32) -> bool {
    let mut p = 0u32;
    for i in 0..15 {
        if y & (1 << i) != 0 {
            p ^= GF16_EXP[i] as u32;
        }
    }
    s[0] = p;
    p = 0;
    for i in 0..3 {
        for j in 0..5 {
            if y & (1u32 << (5 * i + j)) != 0 {
                p ^= GF16_EXP[j * 3] as u32;
            }
        }
    }
    s[1] = p;
    p = 0;
    for i in 0..5 {
        for j in 0..3 {
            if y & (1u32 << (3 * i + j)) != 0 {
                p ^= GF16_EXP[j * 5] as u32;
            }
        }
    }
    s[2] = p;
    s[0] != 0 || s[1] != 0 || s[2] != 0
}

/// Compute coefficients of the error-locator polynomial. Returns its degree.
fn bch15_5_calc_omega(o: &mut [u32; 3], s: &[u32; 3]) -> i32 {
    o[0] = s[0];
    let s02 = gf16_mul(s[0], s[0]);
    let dd = s[1] ^ gf16_mul(s[0], s02);
    let tt = s[2] ^ gf16_mul(s02, s[1]);
    o[1] = if dd != 0 { gf16_div(tt, dd) } else { 0 };
    o[2] = dd ^ gf16_mul(s[0], o[1]);
    let mut d = 3;
    while d > 0 && o[d as usize - 1] == 0 {
        d -= 1;
    }
    d
}

/// Find roots of the error-locator polynomial.
/// Returns the number of roots found, or `-1` if not enough were found (decode failure).
fn bch15_5_calc_epos(epos: &mut [u32; 3], s: &[u32; 3]) -> i32 {
    let mut o = [0u32; 3];
    let d = bch15_5_calc_omega(&mut o, s);
    let mut nerrors = 0;
    if d == 1 {
        epos[nerrors] = GF16_LOG[o[0] as usize] as u32;
        nerrors += 1;
    } else if d > 0 {
        for i in 0..15 {
            // i2 = gf16_log[gf16_exp[i<<1]]
            let i2 = GF16_LOG[GF16_EXP[(i << 1) as usize] as usize] as usize;
            // gf16_exp[i+i2] ^ gf16_hmul(o[0], i2) ^ gf16_hmul(o[1], i) ^ o[2]
            let lhs = GF16_EXP[i + i2] as u32
                ^ gf16_hmul(o[0], i2 as u32)
                ^ gf16_hmul(o[1], i as u32)
                ^ o[2];
            if lhs == 0 {
                epos[nerrors] = i as u32;
                nerrors += 1;
            }
        }
        if (nerrors as i32) < d {
            return -1;
        }
    }
    nerrors as i32
}

/// Corrects the received 15-bit codeword `*y` if possible.
/// On success returns the number of errors corrected (0..=3) and writes the
/// corrected codeword into `*y`. Returns `-1` if decoding failed; `*y` is
/// left unchanged.
pub fn bch15_5_correct(y_ref: &mut u32) -> i32 {
    let mut s = [0u32; 3];
    let mut epos = [0u32; 3];
    let mut y = *y_ref;
    if !bch15_5_calc_syndrome(&mut s, y) {
        return 0;
    }
    let nerrors = bch15_5_calc_epos(&mut epos, &s);
    if nerrors > 0 {
        for i in 0..nerrors as usize {
            y ^= 1u32 << epos[i];
        }
        // Verify by re-encoding the top 5 bits — cheaper than recomputing the syndrome.
        if bch15_5_encode(y >> 10) == y {
            *y_ref = y;
            return nerrors;
        }
    }
    -1
}

/// Encodes a 5-bit value into a 15-bit BCH(15,5) codeword.
/// Each data bit selects one of five generator masks; result is their XOR.
#[inline]
pub fn bch15_5_encode(x: u32) -> u32 {
    (x & 1).wrapping_neg() & 0x0537
        ^ ((x >> 1) & 1).wrapping_neg() & 0x0A6E
        ^ ((x >> 2) & 1).wrapping_neg() & 0x11EB
        ^ ((x >> 3) & 1).wrapping_neg() & 0x23D6
        ^ ((x >> 4) & 1).wrapping_neg() & 0x429B
}

#[cfg(test)]
mod tests {
    use super::*;

    #[inline]
    fn hamming(a: u32, b: u32) -> u32 {
        (a ^ b).count_ones()
    }

    #[test]
    fn encode_minimum_distance() {
        // BCH(15,5) has minimum distance 7 (≥7 between any two codewords).
        let mut codes = [0u32; 32];
        for i in 0..32 {
            codes[i] = bch15_5_encode(i as u32);
            assert!(codes[i] < (1 << 15), "code 0x{:X} out of 15-bit range", codes[i]);
        }
        for i in 0..32 {
            for j in (i + 1)..32 {
                let d = hamming(codes[i], codes[j]);
                assert!(d >= 7, "codes for {} and {} differ in only {} bits", i, j, d);
            }
        }
    }

    #[test]
    fn correct_zero_errors() {
        for i in 0..32 {
            let mut y = bch15_5_encode(i as u32);
            let original = y;
            let n = bch15_5_correct(&mut y);
            assert_eq!(n, 0, "no syndrome on a clean codeword for data {}", i);
            assert_eq!(y, original);
        }
    }

    #[test]
    fn correct_single_bit_error() {
        for i in 0..32 {
            let codeword = bch15_5_encode(i as u32);
            for flip in 0..15 {
                let mut y = codeword ^ (1 << flip);
                let n = bch15_5_correct(&mut y);
                assert_eq!(n, 1, "data {} flip bit {}: expected 1 correction", i, flip);
                assert_eq!(y, codeword);
            }
        }
    }

    #[test]
    fn correct_double_bit_error() {
        for i in 0..32 {
            let codeword = bch15_5_encode(i as u32);
            // sample double-flips
            for a in 0..15 {
                for b in (a + 1)..15 {
                    let mut y = codeword ^ (1 << a) ^ (1 << b);
                    let n = bch15_5_correct(&mut y);
                    assert_eq!(n, 2, "data {} flips {} {}: expected 2", i, a, b);
                    assert_eq!(y, codeword);
                }
            }
        }
    }

    #[test]
    fn correct_triple_bit_error() {
        for i in 0..32 {
            let codeword = bch15_5_encode(i as u32);
            for a in 0..15 {
                for b in (a + 1)..15 {
                    for c in (b + 1)..15 {
                        let mut y = codeword ^ (1 << a) ^ (1 << b) ^ (1 << c);
                        let n = bch15_5_correct(&mut y);
                        assert_eq!(n, 3, "data {} flips {} {} {}", i, a, b, c);
                        assert_eq!(y, codeword);
                    }
                }
            }
        }
    }

    #[test]
    fn exhaustive_decode_matches_nearest() {
        // Replicates the disabled `#if 0` main() in bch15_5.c: every 15-bit input
        // should either decode to the nearest codeword (if Hamming distance ≤ 3)
        // or be rejected (returns -1).
        let mut codes = [0u32; 32];
        for i in 0..32 { codes[i] = bch15_5_encode(i as u32); }
        for input in 0u32..0x8000 {
            // Find the nearest codeword.
            let (nearest, nearest_d) = codes.iter().enumerate()
                .map(|(_, &c)| (c, hamming(input, c)))
                .min_by_key(|&(_, d)| d).unwrap();
            let mut y = input;
            let n = bch15_5_correct(&mut y);
            if n >= 0 {
                assert_eq!(y, nearest,
                    "0x{:04X}: decoded to 0x{:04X}, nearest is 0x{:04X} (d={})",
                    input, y, nearest, nearest_d);
            } else {
                // -1 means rejection. Should only happen when nearest is > 3 away.
                assert!(nearest_d > 3,
                    "0x{:04X}: rejected but nearest 0x{:04X} only {} bits away",
                    input, nearest, nearest_d);
            }
        }
    }
}
